title: Marianna Nezhurina # your name (or website title) here
logo: "/images/20200112_151931.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br><br>
Hi! I'm Marianna and this is my Portfolio
<br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
