title: Marianna Nezhurina
logo: /images/logo.jpg
description: >
  Hello! My name is Marianna and this is my portfolio.
  <br><br>
  <a href="https://www.linkedin.com/in/marianna-nezhurina-957848145/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
